# Set up

In [32]:
import pandas as pd
import numpy as np

In [33]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set

test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set

In [34]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [35]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


# Task 8

In [36]:
age_median = train['Age'].median()
age_mode = train['Age'].mode()[0]

print(f"Median of Age column : {age_median}")
print(f"Mode of Age column : {age_mode}")

train['Age'].fillna(age_median, inplace=True)
test['Age'].fillna(age_median, inplace=True)

Median of Age column : 28.0
Mode of Age column : 24.0


# Task 9

In [37]:
train['Embarked'].replace({'S':0,
                           'C':1,
                           'Q':2}, inplace=True)
embarked_mode = train['Embarked'].mode()[0]

print(f"Mode of Embarked column : {embarked_mode}")

train['Embarked'].fillna(embarked_mode, inplace=True)
test['Embarked'].fillna(embarked_mode, inplace=True)


Mode of Embarked column : 0.0


In [38]:
train['Sex'].replace({'male':0,
                      'female':1}, inplace=True)
sex_mode = train['Sex'].mode()[0]

print(f"Mode of Sex column : {sex_mode}")

train['Sex'].fillna(sex_mode, inplace=True)
test['Sex'].fillna(sex_mode, inplace=True)

Mode of Sex column : 0


# Task 10

In [44]:
data = np.array(train[['Pclass', 'Sex', 'Age', 'Embarked']].values, dtype=float)

print(data.shape)
print(data)

(891, 4)
[[ 3.  0. 22.  0.]
 [ 1.  1. 38.  1.]
 [ 3.  1. 26.  0.]
 ...
 [ 3.  1. 28.  0.]
 [ 1.  0. 26.  1.]
 [ 3.  0. 32.  2.]]
